### ISSUE TITLE
Cannot change log driver - daemon.json does not exist

### ISSUE THREAD

**Issue by OmpahDev** [docker/for-aws#101]
I have a deployed Docker for AWS stack with CloudFormation, and now I've decided I want to switch from CloudWatch to LogEntries as the logging driver.. I'm trying to follow the instructions at https://docs.docker.com/engine/admin/logging/overview/, but it's not working because there is no /etc/docker/daemon.json file, and 'dockerd' is not a valid command. 

I can't just make the change from within CloudFormation because I cannot redeploy these boxes (the change **must** be made directly within the existing EC2 instances without terminating them, that is non-negotiable), so how do I do this?

**Comment by FrenchBen** [comment]
Customizing the docker engine underneath it all isn't currently easy to do, as stopping docker will also kill your current session (also a wrong daemon config will break the instance)
We're working on moving out the ssh container to be at a lower-level, allowing users to customize the engine and the drivers they want. 

During a `docker service create` or `docker stack deploy`, you can easily add the desired `--log-driver` and `--log-opt` to the deployment.

Additionally, if this is a true show-stopper for you, you can easily edit the userData passed to the instance for your log-driver to be used instead of CloudWatch.
