### ISSUE TITLE
Upgrade to 17.2.1-CE

### ISSUE THREAD

**Issue by jgallen23** [docker/for-aws#141]
### Expected behavior

Want to be able to upgrade my docker swarm to 17.2.1-CE to address this bug: https://github.com/moby/moby/issues/35941.

### Actual behavior

Stable build is 17.2.0

Is there a way to manually do this or do we need to wait for a new CF template?

**Comment by FrenchBen** [comment]
We're currently in the process of publishing the 17.12.1-CE and will push an update to the Docs once done. There's a more active thread/discussion on our Community Slack channel. Feel free to join the discussion there.

**Comment by vce-xx** [comment]
@FrenchBen Providing feedback on this to ensure the team is aware : 17.12.1-CE has this issue [Can't stop docker container](https://github.com/moby/moby/issues/35933) which leads other issues like this [Unable to remove network "has active endpoints"](https://github.com/moby/moby/issues/17217) and like this one [Lots of “failed to allocate gateway: Address already in use” in Docker CE 17.09.0](https://github.com/moby/moby/issues/35204)
Since 17.12.1-CE made its way to Docker for AWS Stable, Docker for AWS became unusable for us.

**Comment by FrenchBen** [comment]
@vce-xx thanks for the feedback and linking to the proper issues. I'll make sure to push the latest patch once available.

**Comment by hrajchert** [comment]
Hi, sry to bother. We currently have d4aws in production using a version of docker engine `Docker CE for AWS 17.06.1-ce (17.06.1-ce-aws1)`. 

We are experiencing some problems where some host daemon starts consuming a lot of CPU, becomes kind of unresponsive and the autoscaling group sometimes kill the instance directly.

We wanted to upgrade to the latest version to fix that problem but in the slack channel they pointed me to this issue, which from what I can understand seems more dangerous than the problem we currently have.

My question is, is there an intermediate template version that fix the daemon going awol and don't have this issue? Like, which was the latest stable version?

Or do you know how much of a priority this bug is so I can make an idea of when it's probably resolved?

Thank you all and sry if this is off topic.

**Comment by vce-xx** [comment]
@hrajchert On the slack community, some advised to rollback on 17.09.1. I can't tell if the CPU issue was solved on that version however. 
I can't rollback to 17.09.1 because this version isn't available from the template archive page. I opened an issue for that : [Missing template for CE 17.09 in Docker for AWS template archive](https://github.com/docker/docker.github.io/issues/6251)

**Comment by hrajchert** [comment]
Just trying urls found this one http://editions-us-east-1.s3.amazonaws.com/aws/stable/17.09.0/Docker.tmpl

**Comment by FrenchBen** [comment]
http://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl is now 18.03.0-ce

**Comment by vce-xx** [comment]
@FrenchBen How can we upgrade the stable channel to 18.03.1-ce ?

**Comment by jgallen23** [comment]
I have the same question - we need to get on 18.03.1.  Not sure if we should just spin up a new swarm completely or upgrade

**Comment by joeabbey** [comment]
Updated Docker for AWS to 18.09.2-ce.

https://download.docker.com/aws/stable/Docker.tmpl
https://download.docker.com/aws/stable/18.09.2-ce/Docker.tmpl
