### ISSUE TITLE
Is Docker for AWS 17.03.0-ce-aws1 different from Docker for AWS 1.13.1 (ga-2) ?

### ISSUE THREAD

**Issue by goloroden** [docker/for-aws#16]
Basically, the title already says it all:

Has Docker for AWS 1.13.1 (ga-2) just been relabelled, now that Docker for AWS 17.03.0-ce-aws1 is out, or are there any actual changes?

**Comment by kencochrane** [comment]
@goloroden sorry for the confusion. 

The release notes are listed here: https://docs.docker.com/docker-for-aws/release-notes/ but due to the CE/EE release the docs were in flux, and some things were missed. 

I have submitted a PR to update them here. https://github.com/docker/docker.github.io/pull/2097

Besides being relabeled we added
- r4 EC2 instance types [#9] 
- `ELBDNSZoneID` output to make it easier to interact with Route53 [#8]

let me know if you have any other questions.

**Comment by goloroden** [comment]
Perfect, that clarifies everything :-)
