### ISSUE TITLE
AWS CloudFormation template failing

### ISSUE THREAD

**Issue by avdvyver01** [docker/for-aws#21]
Hi,

I am trying to deploy Docker for AWS in my own VPC. The VPC has the required prerequisites (required permissions, 3 x public subnets with routing table and route to internet gateway). I am using the "Docker for AWS 17.03.0-ce (edge)" template but it keeps failing with:

CREATE_FAILED	AWS::AutoScaling::AutoScalingGroup	ManagerAsg	Received 1 SUCCESS signal(s) out of 3. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

At this point the rollback starts. Can anyone please assist me to fix this problem? I have tried to change the health check from 300 to 900 (HealthCheckGracePeriod": 900) and to use larger instance types, but I still get the same result. 

Thank you

**Comment by avdvyver01** [comment]
I found a more specific information - with above is most likely due to the fact that the instance does not return a healthy state to the ELB which is most likely due to the below error message:

Unable to find image 'docker4x/shell-aws:aws-v17.03.0-ce' locally docker: Error response from daemon: manifest for docker4x/shell-aws:aws-v17.03.0-ce not found.

This causes the template to keep on terminating the instances and recreating them in a continuous loop.

**Comment by ambrons** [comment]
@avdvyver01 If you're using a different network block from the default `172.31.0.0/16` it's like the same issue as #18 I reported a week or so ago.  I'm not sure @kencochrane has had a chance to fix this yet, though I believe they have a solution moving forward.

There's good news though, there's a work around.  If you update the two SecurityGroups: `NodeVpcSG-<unique_id>` and `SwarmWideSG-<unique_id>` to match your defined vpc's network range while it's in the process of deploying the managers and workers it'll start working will the cloudformation is still running.

The issue is the have those 2 security groups hardcoded to `172.31.0.0/16` and so the ELB fails to connect to check the health so they keep restarting over and over until the cloudformation times out.

**Comment by avdvyver01** [comment]
Yep, sorted. Thanks for your help @ambrons - much appreciated!

If I may, is there a specific reason why the instances are deployed into public subnets? Is there any issue with me deploying them to 3 x private subnets that has internet access and that I have access to?

**Comment by kencochrane** [comment]
@avdvyver01 I haven't personally tested deploying them to 3 private subnets, but as long as they have internet access (able to download images from docker hub) I think it should be fine, If not let us know.

**Comment by avdvyver01** [comment]
Hi @kencochrane. I have successfully deployed the CF template into private subnets. I have also modified it not to assign elastic IPs to the EC2 instances which also deployed successfully. Thanks again for your assistance!

**Comment by kencochrane** [comment]
@avdvyver01 that is good news. One quick question, we don't assign elastic IPS to the EC2 instances, do you mean public IPs?

**Comment by avdvyver01** [comment]
@kencochrane apologies, yes, thats what I meant

**Comment by wickstargazer** [comment]
Hi, I had a bit of a confusion regarding the vpcCidr. Is this suppose to be what can connect to the managers and the workers cidrs? If so, then the health-check from the external load-balancer is always failing. This was causing the Auto-Scaling to go onto an infinite loop. 
I fixed by adding the source from loadbalancer port 44554 to the ManagerVpcSG. That solved the problem

I did so because i need everything to be under private VPC with NAT setup. I think the guys should add an option to setup a NAT Gateway and boolean for PublicIPBinding :) 

[cf_docker_template.zip](https://github.com/docker/for-aws/files/1169405/cf_docker_template.zip)

P.S. Also, if its possible to check the region and hide the publicAZ3 if there is none that would be great!

@avdvyver01 I also tried to deploy the template into the private subnet. But i am getting a connection refused when trying to ssh to the docker manager. Any help would be much appreciated.

**Comment by kencochrane** [comment]
@wickstargazer 

> Hi, I had a bit of a confusion regarding the vpcCidr.  Is this suppose to be what can connect to the managers and the workers cidrs?

It is the CIDR for the VPC that you have configured. If you look at your VPC in the AWS dashboard you should be able to easily find this value.

> I think the guys should add an option to setup a NAT Gateway and boolean for PublicIPBinding :)

Feel free to submit the request so we don't lose track

> Also, if its possible to check the region and hide the publicAZ3 if there is none that would be great!

I agree, but this currently isn't possible with CloudFormation.

**Comment by alukach** [comment]
I ran into the same issue:

Status | Type | Logical ID | Status reason
--- | --- | --- | ---
CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | ManagerAsg | Received 1 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement


For me, the issue was that the "Public" Subnets used were not actually associated with an Internet Gateway (meaning that it wasn't actually a Public Subnet). Thus, the nodes would hang waiting for internet connections on bootup.
