### ISSUE TITLE
Logs do not appear to be going to Cloudwatch on successful messages

### ISSUE THREAD

**Issue by zbruhnke** [docker/for-aws#33]
### Expected behavior
When I launch a service using docker stack deploy (in this case a rails app) I get logs to cloudwatch telling me that puma has started on port 3000

<img width="1037" alt="screenshot 2017-04-18 16 48 47" src="https://cloud.githubusercontent.com/assets/346308/25154603/ecff6e6e-2456-11e7-9da4-9f8895937fd0.png">

### Actual behavior

The above is what I would expect, However when it successfully answers API requests no logs are writen to cloudwatch. Im not sure why this is but it seems this is a bug unless there is something I am doing differently than I should - I'm using Docker for AWS's cloudformation template with the only changes being instance sizes - so no edits to anything material to this problem.

### Steps to reproduce the behavior

  1. Deploy a service using a docker stack file - simple one attached below for reference

<img width="596" alt="screenshot 2017-04-18 16 51 56" src="https://cloud.githubusercontent.com/assets/346308/25154718/65228c82-2457-11e7-8a7a-62a344f7b7e6.png">

  2. Go pull up the logs on Cloudwatch when you first boot it up it will show logs - if there are errors the logs seem to also appear, however failed requests appear to show no errors at all - Doesn't help much with that ELK stack I've setup

**Comment by ambrons** [comment]
I my be miss understanding the behavior here, so I'll reiterate.  You get some logging in cloudwatch for this container, such as it's initialization, but you're missing failed request information.

Based on the above assumption I would suggest that it's possible that Puma or the rails container you're working with does not send errors or all longs to /dev/stdout and /dev/stderr.  You may wish to double check the log configuration for those containers.

FYI if Puma is setup to use a file for logging instead of stdout / stderr you can use the docker build process for the application to map log files to `/dev/stdout` and `/dev/stderr`.

**Comment by zbruhnke** [comment]
you're right - I hadnt overridden STDOUT in the environment i was using for testing this - closing now
