### ISSUE TITLE
Python is Missing from Docker for AWS AMI

### ISSUE THREAD

**Issue by juddflamm** [docker/for-aws#37]
### Expected behavior
To be able to connect to a master node of my swarm and successfully execute a modern version of python.

### Actual behavior
Python executable is not found

### Information
I am using CodeFresh.io to deploy my image (service) to my swarm.  CodeFresh.io has a command called rdocker that uses your host's ssh key to remotely execute docker commands on a master node.  rdocker expects python to be available on the master node.

I've spent most of last night and this morning looking for reasonable solutions.  I've come to the conclusion that the Docker for AWS linux ami (4.9.113-moby) needs to support linux.  Especially since many CI/CD tools like CodeFresh.io and Ansible, etc expect the master node to have python available.

Could you please help me either know how to install python myself, on my master node of my swarm; or update the ami to include it?  apt-get, yum, and even make, all seem to be missing from the ami - I haven't been able to install python myself.

Thank you!

**Comment by friism** [comment]
It's very easy to run any version of Python on Docker for AWS, modern or not:

    docker run -ti python sh

I don't fully understand how the rdocker script works, but I think that ideally the script itself would run on Docker on the remote host. That way it could run in a container image that includes any dependencies it needs. Since I assume the script needs access to the Docker daemon API on the remote host, it would simply mount the Docker socket when run:

    docker run  -v /var/run/docker.sock:/var/run/docker.sock codefresh/rdocker do-something

This is how we're building the Docker platform itself: All components run packaged in containers. And one of the reasons is to avoid different components conflicting because of divergent dependency requirements or incompatible settings.

**Comment by kencochrane** [comment]
@juddflamm moby is a custom linux os built with LinuxKit, the goal is to keep the image size as small as possible, so we only install what is required to get up and running. 

If you want to install python, you can do so using the alpine package manager apk and using sudo.

https://docs.docker.com/docker-for-aws/faqs/#how-do-i-run-administrative-commands

for example:
```
$ sudo apk add --update  python
```
It is important to note, that this will only install it on the one node, and if that node is upgraded, it will need to be installed again, because nodes are recycled on upgrade.

**Comment by juddflamm** [comment]
Thank you @kencochrane - I will try this as a short term work around!

**Comment by juddflamm** [comment]
@friism , I'd like to do what you suggest.  I tried last night - because I found you posting this else where.  But I have one problem still.  Inside the python docker container, I don't have the docker cli.

The rdocker script uses python to setup the remote connection to the docker daemon.  But then, it calls docker cli commands.

How do you get the docker cli into the python container?

Thanks!

**Comment by friism** [comment]
@juddflamm you should be able to either install normally (eg. with `apt-get install docker`) or pull just the Docker CLI binary when building the image like how it's done here:

    https://github.com/docker-library/docker/blob/47d5d4ead8a95871d011b005394c9f2f7af68dab/17.05-rc/Dockerfile#L20

**Comment by juddflamm** [comment]
Thank you VERY much for your speedy help!
