### ISSUE TITLE
Is it safe to add things to the VPC?

### ISSUE THREAD

**Issue by goloroden** [docker/for-aws#4]
Inspired by #3 I wondered whether it is safe to add custom things to the VPC that was created by the *Docker for AWS* template?

Will this cause problems in case of updates, or is it safe to do so?

**Comment by kencochrane** [comment]
@goloroden It depends on what you are going to be adding, but I would say most of the things should be safe. 

One thing to note, if you add new things to the VPC, and then you try to delete the stack you created with the docker for AWS template it will most likely fail, since the VPC will have a dependency that CloudFormation doesn't know about.

**Comment by goloroden** [comment]
Great, thanks 😊
