### ISSUE TITLE
How to Customize Moby Linux Instances

### ISSUE THREAD

**Issue by RehanSaeed** [docker/for-aws#96]
I would like to run an `apk add xyz` command on each node in my swarm to help with my automated deployments. 

I'd like to be able to add this command to the cloud formation template or even better have a text box in AWS where I can paste some bash script when I am creating my swarm.

Since I'm new to cloud formation templates and this is a particularly complicated one, I was hoping to get some guidance on how I can achieve this.

**Comment by friism** [comment]
Docker for AWS is built to run software in containers on top of the Docker platform. What's the software that you'd like to run? Software like Puppet runs well in containers and can drive the Docker platform API to deploy additional software.

It may not be a good idea to modify the cloudformation template because changes made there may not apply as you scale or when nodes are replaced, and will not be a part of updated cloudformation templates (with new Docker versions) from Docker Inc.

Let us know what you're trying to do and we'll help get it working.

**Comment by RehanSaeed** [comment]
I'm trying to use Octopus Deploy to download my docker-stack.yml file and run a docker login and stack deploy command. 

Octopus works by SSH'ing into one of the boxes before it can run its deployment. This requires a platform supported by .NET Core (Moby Linux/Alpine is not yet supported but is being worked on) so that Octopus Deploy can download a cross platform executable called Calamari. Alternatively, I can install Mono on Moby Linux which is available and works, so that's what I'm trying to do.

If there is a better way of deploying my stack file, I'd like to hear it.

**Comment by friism** [comment]
Unfortunately it doesn't appear like Calamari can run in a container. It should be relatively simple though:

1. check if the deployment is using Docker (if not, just use the regular flow)
2. ssh to the machine
3. instead of running `calamari` directly on the host, run `docker run -v /var/run/docker.sock:/var/run/docker.sock octopusdeploy/calamari <some-script>`

From inside of that container, Octopus can drive the Docker platform through the mounted API and do it's thing. And the neat thing is that the user doesn't have to worry about whether this or that software is available on the host (eg. the .NET Core requirements).

cc @PaulStovell

Here's a strawman Dockerfile for calamari:

```
FROM ubuntu:16

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libunwind8 \
        libunwind8-dev \
        gettext \
        libicu-dev \
        liblttng-ust-dev \
        libcurl4-openssl-dev \
        libssl-dev \
        uuid-dev \
        unzip \
    && rm -rf /var/lib/apt/lists/*

# TODO get calamari
```
